// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// Command: npx gltfjsx@6.2.3 public/models/MacBook Pro.glb -o src/components/MacBookPro.jsx -r public
// Laptop / MacBook Pro by Alex Safayan [CC-BY] (https://creativecommons.org/licenses/by/3.0/) via Poly Pizza (https://poly.pizza/m/27hcX_w47Jb)
// */

// import { useGLTF, useTexture } from "@react-three/drei";
// import React from "react";

// export function MacBookPro(props) {
//   const { nodes, materials } = useGLTF("/models/MacBook Pro.glb");
//   const screeTexture=useTexture('/textures/screen.jpg')
//   return (
//     <group {...props} dispose={null}>
//       <mesh position={[0.02,0.85,-0.66]}>
//         <planeGeometry args={[2.55,1.55]}/>
//         <meshBasicMaterial map={screeTexture}/>
//       </mesh>
//       <mesh
//         geometry={nodes.mesh485226736.geometry}
//         material={materials.mat16}
//       />
//       <mesh
//         geometry={nodes.mesh485226736_1.geometry}
//         material={materials.mat23}
//       />
//       <mesh
//         geometry={nodes.mesh485226736_2.geometry}
//         material={materials.mat17}
//       />
//       <mesh
//         geometry={nodes.mesh485226736_3.geometry}
//         material={materials.mat15}
//       />
//       <mesh
//         geometry={nodes.mesh256948792.geometry}
//         material={materials.mat16}
//       />
//       <mesh
//         geometry={nodes.mesh256948792_1.geometry}
//         material={materials.mat23}
//       />
//       <mesh
//         geometry={nodes.mesh256948792_2.geometry}
//         material={materials.mat17}
//       />
//       <mesh
//         geometry={nodes.mesh256948792_3.geometry}
//         material={materials.mat25}
//       />
//     </group>
//   );
// }
// useGLTF.preload("/models/MacBook Pro.glb");



/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/MacBook Pro.glb -o src/components/MacBookPro.jsx -r public
Laptop / MacBook Pro by Alex Safayan [CC-BY] (https://creativecommons.org/licenses/by/3.0/) via Poly Pizza (https://poly.pizza/m/27hcX_w47Jb)
*/

import React, { useEffect, useMemo } from "react";
import * as THREE from "three";
import { useGLTF } from "@react-three/drei";

export function MacBookPro(props) {
  const { nodes, materials } = useGLTF("/models/MacBook Pro.glb");
  const { video, texture } = useMemo(() => {
    const video = document.createElement("video");

    video.src = "/videos/Website video.mp4";
    video.crossOrigin = "anonymous";
    video.loop = true;
    video.muted = true;
    video.playsInline = true;

    const texture = new THREE.VideoTexture(video);

    texture.flipY = true;
    texture.colorSpace = THREE.SRGBColorSpace;

    return {
      video,
      texture,
    };
  }, []);

  useEffect(() => {
    video.play().catch(() => { });
  }, [video]);
  return (
    <group {...props} dispose={null}>
      <mesh position={[0.02, 0.85, -0.66]}>
        <planeGeometry args={[2.55, 1.55]} />

        <meshBasicMaterial
          map={texture}
          toneMapped={false}
        />
      </mesh>
      <mesh
        geometry={nodes.mesh485226736.geometry}
        material={materials.mat16}
      />
      <mesh
        geometry={nodes.mesh485226736_1.geometry}
        material={materials.mat23}
      />
      <mesh
        geometry={nodes.mesh485226736_2.geometry}
        material={materials.mat17}
      />
      <mesh
        geometry={nodes.mesh485226736_3.geometry}
        material={materials.mat15}
      />
      <mesh
        geometry={nodes.mesh256948792.geometry}
        material={materials.mat16}
      />
      <mesh
        geometry={nodes.mesh256948792_1.geometry}
        material={materials.mat23}
      />
      <mesh
        geometry={nodes.mesh256948792_2.geometry}
        material={materials.mat17}
      />
      <mesh
        geometry={nodes.mesh256948792_3.geometry}
        material={materials.mat25}
      />
    </group>
  );
}
useGLTF.preload("/models/MacBook Pro.glb");
