/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

// import React, { useRef } from 'react'
// import { useGLTF } from '@react-three/drei'

import React, { useMemo, useEffect } from "react";
import * as THREE from "three";
import { useGLTF } from "@react-three/drei";



export function Mobile(props) {
    const { nodes, materials } = useGLTF('/models/Mobile.glb');
    const videoTexture = useMemo(() => {
        const video = document.createElement("video");

        video.src = "/videos/video1.mp4";
        video.crossOrigin = "anonymous";
        video.loop = true;
        video.muted = true;
        video.playsInline = true;

        const texture = new THREE.VideoTexture(video);
        texture.flipY = true;

        return {
            video,
            texture,
        };
    }, []);

    useEffect(() => {
        videoTexture.video.play().catch(() => { });
    }, [videoTexture]);
    return (
        <group {...props} dispose={null}>
            <group position={[-0.003, 0.208, -0.041]} scale={0.01}>
                <group position={[0.099, 7.825, 4.123]}>
                    <group position={[10.634, 18.946, 0.826]} scale={[1.018, 1.018, 1.037]}>
                        <mesh
                            geometry={nodes.Back_Side.geometry}
                            material={materials.Material_6}
                            position={[-10.041, -18.066, -9.559]}
                            rotation={[-Math.PI, 0, -Math.PI]}
                            scale={[1.079, 1.08, 1.065]}
                        />
                        <group position={[-139.661, 74.636, 0.258]} scale={[0.983, 0.982, 0.964]}>
                            <mesh
                                geometry={nodes.Rectangle_7.geometry}
                                material={materials.Material_4}
                                position={[-1.512, 11.96, 0]}
                                rotation={[0, 1.571, 0]}
                                scale={[1.037, 1.018, 1.018]}
                            />
                            <mesh
                                geometry={nodes.Rectangle_9.geometry}
                                material={materials.Material_31}
                                position={[0.773, 61.218, -0.259]}
                                rotation={[0, -1.571, 0]}
                                scale={[1.037, 1.018, 1.018]}
                            />
                        </group>
                        {/* <mesh
              geometry={nodes.Screen.geometry}
              material={materials.Material_29}
              position={[-10.451, -18.606, 14.551]}
              scale={[0.983, 0.982, 0.964]}
            /> */}
                        <mesh
                            geometry={nodes.Screen.geometry}
                            position={[-10.451, -18.606, 14.551]}
                            scale={[0.983, 0.982, 0.964]}
                        >
                            <meshBasicMaterial
                                map={videoTexture.texture}
                                toneMapped={false}
                            />
                        </mesh>


                        <mesh
                            geometry={nodes.Screen_Border.geometry}
                            material={materials.Material_30}
                            position={[-10.451, -18.606, 14.386]}
                            rotation={[-Math.PI, 0, -Math.PI]}
                            scale={[1.079, 1.08, 1.065]}
                        />
                    </group>
                    <group position={[52.978, 191.101, -23.025]} scale={1.159}>
                        <group position={[26.183, 23.962, -0.782]} scale={0.864}>
                            <mesh
                                geometry={nodes.Ellipse_10002.geometry}
                                material={materials.Material_11}
                                position={[-0.167, -0.123, -2.074]}
                                rotation={[-Math.PI, 0, -Math.PI]}
                            />
                            <mesh
                                geometry={nodes.Ellipse_3004.geometry}
                                material={materials.Material_28}
                                position={[-0.5, 0, 2.5]}
                                rotation={[-Math.PI, 0, -Math.PI]}
                            />
                            <mesh
                                geometry={nodes.Ellipse_4003.geometry}
                                material={materials.Material_25}
                                position={[-0.5, -0.185, 1.597]}
                                rotation={[-Math.PI, 0, -Math.PI]}
                            />
                            <mesh
                                geometry={nodes.Ellipse_5003.geometry}
                                material={materials.Material_24}
                                position={[-0.167, -0.123, 1.099]}
                                rotation={[-Math.PI, 0, -Math.PI]}
                            />
                            <mesh
                                geometry={nodes.Ellipse_6005.geometry}
                                material={materials.Material_23}
                                position={[0, 0, 0.496]}
                                rotation={[-Math.PI, 0, -Math.PI]}
                            />
                            <mesh
                                geometry={nodes.Ellipse_8002.geometry}
                                material={materials.Material_27}
                                position={[1.502, -2, -2.32]}
                                rotation={[-Math.PI, 0, -Math.PI]}
                            />
                            <mesh
                                geometry={nodes.Ellipse_9002.geometry}
                                material={materials.Material_26}
                                position={[-3.496, 1.998, -2.32]}
                                rotation={[-Math.PI, 0, -Math.PI]}
                                scale={0.5}
                            />
                        </group>
                        <group position={[-25.302, -2.156, -0.782]} scale={0.864}>
                            <mesh
                                geometry={nodes.Ellipse_3003.geometry}
                                material={materials.Material_22}
                                position={[-0.5, 0, 2.5]}
                                rotation={[-Math.PI, 0, -Math.PI]}
                            />
                            <mesh
                                geometry={nodes.Ellipse_4002.geometry}
                                material={materials.Material_19}
                                position={[-0.5, -0.185, 1.597]}
                                rotation={[-Math.PI, 0, -Math.PI]}
                            />
                            <mesh
                                geometry={nodes.Ellipse_5002.geometry}
                                material={materials.Material_18}
                                position={[-0.167, -0.123, 1.099]}
                                rotation={[-Math.PI, 0, -Math.PI]}
                            />
                            <mesh
                                geometry={nodes.Ellipse_6004.geometry}
                                material={materials.Material_17}
                                position={[0, 0, 0.496]}
                                rotation={[-Math.PI, 0, -Math.PI]}
                            />
                            <mesh
                                geometry={nodes.Ellipse_8001.geometry}
                                material={materials.Material_21}
                                position={[1.502, -2, -2.32]}
                                rotation={[-Math.PI, 0, -Math.PI]}
                            />
                            <mesh
                                geometry={nodes.Ellipse_9001.geometry}
                                material={materials.Material_20}
                                position={[-3.496, 1.998, -2.32]}
                                rotation={[-Math.PI, 0, -Math.PI]}
                                scale={0.5}
                            />
                        </group>
                        <group position={[25.454, -30.011, -0.782]} scale={0.864}>
                            <mesh
                                geometry={nodes.Ellipse_3002.geometry}
                                material={materials.Material_16}
                                position={[-0.5, 0, 2.5]}
                                rotation={[-Math.PI, 0, -Math.PI]}
                            />
                            <mesh
                                geometry={nodes.Ellipse_4001.geometry}
                                material={materials.Material_13}
                                position={[-0.5, -0.185, 1.597]}
                                rotation={[-Math.PI, 0, -Math.PI]}
                            />
                            <mesh
                                geometry={nodes.Ellipse_5001.geometry}
                                material={materials.Material_12}
                                position={[-0.167, -0.123, 1.099]}
                                rotation={[-Math.PI, 0, -Math.PI]}
                            />
                            <mesh
                                geometry={nodes.Ellipse_6003.geometry}
                                material={materials.Material_10}
                                position={[0, 0, 0.496]}
                                rotation={[-Math.PI, 0, -Math.PI]}
                            />
                            <mesh
                                geometry={nodes.Ellipse_8.geometry}
                                material={materials.Material_15}
                                position={[1.502, -2, -2.32]}
                                rotation={[-Math.PI, 0, -Math.PI]}
                            />
                            <mesh
                                geometry={nodes.Ellipse_9.geometry}
                                material={materials.Material_14}
                                position={[-3.496, 1.998, -2.32]}
                                rotation={[-Math.PI, 0, -Math.PI]}
                                scale={0.5}
                            />
                        </group>
                        <mesh
                            geometry={nodes.Cube_2.geometry}
                            material={materials.Material_5}
                            position={[0.243, -2.526, -1.133]}
                            rotation={[-Math.PI, 0, -Math.PI]}
                            scale={0.863}
                        />
                        <mesh
                            geometry={nodes.Ellipse_3001.geometry}
                            material={materials.Material_9}
                            position={[-25.872, -41.025, -1.383]}
                            rotation={[Math.PI, 0, Math.PI]}
                            scale={[0.857, 0.857, 0.846]}
                        />
                        <group position={[-25.872, 36.929, -1.908]} scale={[0.939, 0.939, 0.846]}>
                            <mesh
                                geometry={nodes.Ellipse002.geometry}
                                material={materials.Material_7}
                                position={[0.129, 0.391, -2.253]}
                                rotation={[-Math.PI, 0, -Math.PI]}
                                scale={[1, 1, 1.11]}
                            />
                            <mesh
                                geometry={nodes.Ellipse003.geometry}
                                material={materials.Material_8}
                                position={[0.002, 0, 0.336]}
                                rotation={[-Math.PI, 0, -Math.PI]}
                                scale={[0.913, 0.913, 1]}
                            />
                        </group>
                    </group>
                    <group position={[-11.5, 252.794, 15.883]}>
                        <group position={[11.579, -12.261, 1.281]}>
                            <mesh
                                geometry={nodes.Ellipse.geometry}
                                material={materials.Material_1}
                                position={[27.831, 0.003, -0.814]}
                            />
                            <mesh
                                geometry={nodes.Ellipse_2.geometry}
                                material={materials.Material_0}
                                position={[27.831, 0.003, -0.346]}
                            />
                            <mesh
                                geometry={nodes.Rectangle.geometry}
                                material={materials.Material_2}
                                position={[0, 0, -0.7]}
                            />
                        </group>
                        <mesh
                            geometry={nodes.Rectangle_5.geometry}
                            material={materials.Material_3}
                            position={[11.5, 8.794, 0.2]}
                        />
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/models/Mobile.glb')